export const FETCH_INIT_STATE = 'FETCH_INIT_STATE';
export type FETCH_INIT_STATE = typeof FETCH_INIT_STATE;

export const TOGGLE_PERSISTENT_MENU = 'TOGGLE_PERSISTENT_MENU';
export type TOGGLE_PERSISTENT_MENU = typeof TOGGLE_PERSISTENT_MENU;

export const FETCH_PERSISTENT_MENU  = 'FETCH_PERSISTENT_MENU ';
export type FETCH_PERSISTENT_MENU = typeof FETCH_PERSISTENT_MENU;